self_id = 1
raft_listen = "0.0.0.0:50051"
fs_listen = "0.0.0.0:50052"
cache_capacity_bytes = 536870912
block_size_bytes = 4194304
grpc_chunk_size_bytes = 1048576

[[peers]]
id = 1
addr = "arustio-node1:50051"

[[peers]]
id = 2
addr = "arustio-node2:50051"

[[peers]]
id = 3
addr = "arustio-node3:50051"
